package uz.amon.domain.enums;

public enum ComplaintStatus
{
    NOT_CREATED,
    SEND,
    ANSWERED,
    CREATED_NOT_SENDED, SENDED_WAIT_DOCTOR_ANSWER, DOCTOR_WRITING_ANSWER, REJECTED_BY_DOCTOR, DOCTOR_ACCEPTED_NOT_ANSWERED, REJECT
}
